### ISSUE TITLE
二维码没能被加载出来

### ISSUE THREAD

**Issue by luowuyao** [amchii/ZhiArchive#2]
环境：AMD Ryzen5 3500c(x86)(chromeos的linux容器) Docker version 26.1.4, build 5650f9b
情况：在运行容器后登陆http://127.0.0.1:9090/zhi/login，其无法加载出二维码。尝试手动替换zhihu.state.json，无果，并未能成功抓录下回答与文章
![Screenshot 2024-06-21 23 47 23](https://github.com/amchii/ZhiArchive/assets/107822133/d89807ea-37d2-4683-ab52-b6771004fb2f)

希望确认下到底是我的环境问题还是知乎的登录二维码接口更新掉了

**Comment by amchii** [comment]
> 希望确认下到底是我的环境问题还是知乎的登录二维码接口更新掉了

你好，目前是可以正确获取登录二维码的吗。
你这个出不来可能是因为`login_worker`没有起来，或者是已经先打开这个页面获取登录二维码但没有扫描，`login_worker`一直在等待上个二维码。可以尝试删除redis中`zhi_archive:login`开头的key（等5分钟也可以）并重启服务。
记得看日志的输出内容。

**Comment by amchii** [comment]
@luowuyao 优化了下登录二维码的获取和刷新，主要是同时打开多个知乎登录页面，会复用同一个二维码，可以再试试👀

**Comment by luowuyao** [comment]
谢谢你的回复，这两天没回复你，我在试着往我的一台armbian上（很抱歉我的设备都这么诡异（笑哭））配代理，但配到一半因为某些玄学因素我没配成，所以没法在其他机器上作验证（笑哭）
在你的更新后我依旧没能在chromeos上获取二维码，大概是因为我的环境太诡异导致的。晚些我会补上日志，谢谢你的回应。

**Comment by amchii** [comment]
嗯，某些华为的arm服务器好像不行，docker redis会提示一个内核错误，可能playwright也不能正常运行。想尝试的话可以在你的个人电脑上。

**Comment by luowuyao** [comment]
感谢。最近没能及时回复，非常抱歉。
最近学习了docker的详细教程，对ZhiArchiver有了更好的理解。总结如下：
> 1.最开始使用ZhiArchive项目时，产生了五个容器，这五个容器中redis容器没能正常启动（也可能是只正常启动了api容器，记忆有些模糊了）。出现了没能显示二维码的情况。当时未能保存日志。
> 2.此后得到了你的更新，五个容器统合为了两个，这两个容器中all_workers容器没能正常启动。同样出现了没能显示二维码的情况。
> 3.再之后在windows上复现了同样的问题。日志与4.基本一致。
> 4.在我重装了docker并配置了docker用户组免sudo配置后，使用现版本的docker-compose.yaml，并在新的wifi环境下进行了部署，问题得到了复现。all_workers容器没能正常启动。这是日志。
[_zhiarchive-all_workers-1_logs.txt](https://github.com/user-attachments/files/16120024/_zhiarchive-all_workers-1_logs.txt)
> 5.使用现版本的docker-compose2.yaml，问题得到了修复，五个容器都正常启动，二维码正常显示。
> 6.使用2个月前版本的项目重新部署，也没有问题，五个容器都正常启动，二维码正常显示。

分析了一下变量，得出的结论如下：
1.wifi网络环境可能是影响的因素。代理并没有更换，只是说wifi网络环境。
2.此前使用sudo执行docker命令（或者问题在docker-compose命令没用sudo执行/用sudo执行了）可能是影响的因素。在配置docker用户组后免sudo执行docker和docker-compose命令，问题得到了解决。
该问题应该和代理无关。和提前用代理下载镜像无关。和从镜像源下载代理无关。

最后向作者表示感谢。非常感谢你的项目，ZhiArchive项目本身的功能相当完善，而它同时也是目前仍在维护的知乎用户创作存档工具中为数不多的一员。向你无私的开源精神与维护的热情表达敬意。

**Comment by amchii** [comment]
不用客气哈。我看了下你发的日志：

>   File "/usr/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 6379)

这是redis连接错误，请看**README**描述，使用`docker-compose2.yaml`需要你自己部署redis。
你列举的第4点和第5点中描述的`docker-compose.yaml`和`docker-compose2.yaml`应该是反了，`docker-compose.yaml`的5个容器中包含了redis所以不需要你单独部署。

**Comment by luowuyao** [comment]
咳咳，谢谢回复，的确是反了
以及提另一个小问题：不能保存已禁言用户的内容。

**Comment by amchii** [comment]
你好，我这边试了下是可以的，随便找了一个禁言的知乎用户：
![image](https://github.com/amchii/ZhiArchive/assets/26922464/67e89a31-f784-40d9-9bdf-3f890f6d704f)
有问题记得附上日志。

**Comment by luowuyao** [comment]
详细研究了一下容器的日志，找到原因了：fetch_until的时间设得太迟了，设早些就能爬了
三度感谢
